window.DADOS = {
  "gerado_em": "2026-08-15T21:12:13.851Z",
  "hoje": "2026-08-15",
  "medindo_desde": "2026-07-24T17:20:05.000Z",
  "apps_desde": "2026-08-11T18:28:02.542Z",
  "auto_publica_desde": "2026-08-10",
  "criterio": {
    "produtos_semana": 2,
    "dias_parada": 7,
    "janela_dias": 7,
    "semanas": 12
  },
  "kpis": {
    "liberadas": 16,
    "ativas": 3,
    "usando": 9,
    "nunca_usaram": 7,
    "paradas": 4,
    "com_conta": 10,
    "contas": 9,
    "produtos_total": 253,
    "produtos_7d": 123,
    "descricoes_total": 246,
    "total_estimado": true
  },
  "marcas": [
    {
      "slug": "nicoboco",
      "nome": "Nicoboco",
      "arquetipo": "explorador",
      "tem_conta": true,
      "email": "nicoboco.shop@nicoboco.com.br",
      "produtos": 104,
      "estimado": false,
      "produtos_7d": 104,
      "ativa": true,
      "acessos": 48,
      "buscas": 287,
      "descricoes": 150,
      "envios": 175,
      "primeiro": "2026-08-10T19:02:35.392Z",
      "ultimo": "2026-08-14T16:13:07.048Z",
      "dias": 1
    },
    {
      "slug": "amiska",
      "nome": "Amiska",
      "arquetipo": "sabio",
      "tem_conta": true,
      "email": "missmilliebr@gmail.com",
      "produtos": 55,
      "estimado": true,
      "produtos_7d": 9,
      "ativa": true,
      "acessos": 4,
      "buscas": 27,
      "descricoes": 28,
      "envios": 31,
      "primeiro": "2026-07-28T18:41:18.639Z",
      "ultimo": "2026-08-11T17:47:11.908Z",
      "dias": 4
    },
    {
      "slug": "petit",
      "nome": "Petit",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "anderson@mundotaci.com.br",
      "produtos": 43,
      "estimado": true,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "2026-07-22T20:22:50.872Z",
      "dias": 24
    },
    {
      "slug": "opera-kids",
      "nome": "Ópera Kids",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "contato@operakids.com.br",
      "produtos": 36,
      "estimado": true,
      "produtos_7d": 1,
      "ativa": false,
      "acessos": 45,
      "buscas": 52,
      "descricoes": 17,
      "envios": 12,
      "primeiro": "2026-07-28T11:47:18.529Z",
      "ultimo": "2026-08-12T12:05:03.861Z",
      "dias": 3
    },
    {
      "slug": "andressa-vesti",
      "nome": "Andressa Vesti",
      "arquetipo": "rebelde",
      "tem_conta": true,
      "email": "andressavazpinto@gmail.commx",
      "produtos": 9,
      "estimado": false,
      "produtos_7d": 9,
      "ativa": true,
      "acessos": 23,
      "buscas": 51,
      "descricoes": 19,
      "envios": 12,
      "primeiro": "2026-08-10T16:01:03.796Z",
      "ultimo": "2026-08-14T12:06:46.387Z",
      "dias": 1
    },
    {
      "slug": "optimist-jeans",
      "nome": "Optimist Jeans",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 3,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 3,
      "buscas": 3,
      "descricoes": 4,
      "envios": 5,
      "primeiro": "2026-08-07T13:23:05.929Z",
      "ultimo": "2026-08-07T14:55:31.596Z",
      "dias": 8
    },
    {
      "slug": "optimist-feirinha",
      "nome": "Optimist Feirinha",
      "arquetipo": "",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 2,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 1,
      "descricoes": 0,
      "envios": 2,
      "primeiro": "2026-08-07T13:33:14.591Z",
      "ultimo": "2026-08-07T14:33:01.598Z",
      "dias": 8
    },
    {
      "slug": "monnika-marikinha",
      "nome": "Monnika Marikinha",
      "arquetipo": "amante",
      "tem_conta": true,
      "email": "monnikamarikinhaloja@gmail.com",
      "produtos": 1,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 2,
      "buscas": 1,
      "descricoes": 1,
      "envios": 1,
      "primeiro": "2026-08-06T14:16:43.085Z",
      "ultimo": "2026-08-06T14:20:20.569Z",
      "dias": 9
    },
    {
      "slug": "anne-blanc",
      "nome": "Anne Blanc",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "demissy",
      "nome": "DeMissy",
      "arquetipo": "",
      "tem_conta": true,
      "email": "comercial.danque@gmail.com",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "gitaa",
      "nome": "Gitaa",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano",
      "nome": "Murano",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano-filial",
      "nome": "Murano filial",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "stefani",
      "nome": "Stefani",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "trimix",
      "nome": "Trimix",
      "arquetipo": "heroi",
      "tem_conta": true,
      "email": "salomon@trimix.com.br",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 9,
      "buscas": 28,
      "descricoes": 27,
      "envios": 0,
      "primeiro": "2026-08-04T14:28:52.117Z",
      "ultimo": "2026-08-14T11:49:55.525Z",
      "dias": 1
    },
    {
      "slug": "ttng",
      "nome": "TTNG",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    }
  ],
  "semanas": [
    {
      "inicio": "2026-05-25",
      "fim": "2026-05-31",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-01",
      "fim": "2026-06-07",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-08",
      "fim": "2026-06-14",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-15",
      "fim": "2026-06-21",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-22",
      "fim": "2026-06-28",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-29",
      "fim": "2026-07-05",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-06",
      "fim": "2026-07-12",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-13",
      "fim": "2026-07-19",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 3,
      "novos": 3
    },
    {
      "inicio": "2026-07-20",
      "fim": "2026-07-26",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 5,
      "novos": 2
    },
    {
      "inicio": "2026-07-27",
      "fim": "2026-08-02",
      "produtos": 13,
      "ativas": 2,
      "usaram": 2,
      "cadastros": 5,
      "novos": 0
    },
    {
      "inicio": "2026-08-03",
      "fim": "2026-08-09",
      "produtos": 21,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 7,
      "novos": 2
    },
    {
      "inicio": "2026-08-10",
      "fim": "2026-08-16",
      "produtos": 123,
      "ativas": 3,
      "usaram": 5,
      "cadastros": 9,
      "novos": 2
    }
  ],
  "apps": {
    "auto": {
      "id": "auto",
      "nome": "Piloto automático",
      "prefixo": "app:auto:",
      "kpis": {
        "liberadas": 16,
        "ativas": 2,
        "usando": 2,
        "nunca_usaram": 14,
        "paradas": 0,
        "com_conta": 10,
        "contas": 9,
        "produtos_total": 105,
        "produtos_7d": 105,
        "descricoes_total": 155,
        "total_estimado": false,
        "produtos_atribuidos": 0
      },
      "marcas": [
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 102,
          "estimado": false,
          "produtos_7d": 102,
          "ativa": true,
          "acessos": 39,
          "buscas": 247,
          "descricoes": 147,
          "envios": 150,
          "primeiro": "2026-08-11T18:28:02.542Z",
          "ultimo": "2026-08-14T16:13:07.048Z",
          "dias": 1,
          "produtos_medidos": 102,
          "atribuido": 0
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 3,
          "estimado": false,
          "produtos_7d": 3,
          "ativa": true,
          "acessos": 13,
          "buscas": 38,
          "descricoes": 8,
          "envios": 4,
          "primeiro": "2026-08-13T17:14:37.157Z",
          "ultimo": "2026-08-13T20:22:23.430Z",
          "dias": 2,
          "produtos_medidos": 3,
          "atribuido": 0
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-05-25",
          "fim": "2026-05-31",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-01",
          "fim": "2026-06-07",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-08",
          "fim": "2026-06-14",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-15",
          "fim": "2026-06-21",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-22",
          "fim": "2026-06-28",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-29",
          "fim": "2026-07-05",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-06",
          "fim": "2026-07-12",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-13",
          "fim": "2026-07-19",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 3,
          "novos": 3,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 105,
          "ativas": 2,
          "usaram": 2,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 105,
          "atribuido": 0
        }
      ]
    },
    "manual": {
      "id": "manual",
      "nome": "Manual",
      "prefixo": "app:manual:",
      "kpis": {
        "liberadas": 16,
        "ativas": 0,
        "usando": 9,
        "nunca_usaram": 7,
        "paradas": 0,
        "com_conta": 10,
        "contas": 9,
        "produtos_total": 223,
        "produtos_7d": 0,
        "descricoes_total": 1,
        "total_estimado": true,
        "produtos_atribuidos": 223
      },
      "marcas": [
        {
          "slug": "nicoboco",
          "nome": "Nicoboco",
          "arquetipo": "explorador",
          "tem_conta": true,
          "email": "nicoboco.shop@nicoboco.com.br",
          "produtos": 75,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 75
        },
        {
          "slug": "amiska",
          "nome": "Amiska",
          "arquetipo": "sabio",
          "tem_conta": true,
          "email": "missmilliebr@gmail.com",
          "produtos": 55,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 55
        },
        {
          "slug": "petit",
          "nome": "Petit",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "anderson@mundotaci.com.br",
          "produtos": 43,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 43
        },
        {
          "slug": "opera-kids",
          "nome": "Ópera Kids",
          "arquetipo": "inocente",
          "tem_conta": true,
          "email": "contato@operakids.com.br",
          "produtos": 36,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 1,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "2026-08-12T12:05:03.861Z",
          "ultimo": "2026-08-12T12:05:03.861Z",
          "dias": 3,
          "produtos_medidos": 0,
          "atribuido": 36
        },
        {
          "slug": "andressa-vesti",
          "nome": "Andressa Vesti",
          "arquetipo": "rebelde",
          "tem_conta": true,
          "email": "andressavazpinto@gmail.commx",
          "produtos": 8,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 1,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "2026-08-14T12:06:46.387Z",
          "ultimo": "2026-08-14T12:06:46.387Z",
          "dias": 1,
          "produtos_medidos": 0,
          "atribuido": 8
        },
        {
          "slug": "optimist-jeans",
          "nome": "Optimist Jeans",
          "arquetipo": "governante",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 3,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 3
        },
        {
          "slug": "optimist-feirinha",
          "nome": "Optimist Feirinha",
          "arquetipo": "",
          "tem_conta": true,
          "email": "ecommerce@optimistjeans.com.br",
          "produtos": 2,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 2
        },
        {
          "slug": "monnika-marikinha",
          "nome": "Monnika Marikinha",
          "arquetipo": "amante",
          "tem_conta": true,
          "email": "monnikamarikinhaloja@gmail.com",
          "produtos": 1,
          "estimado": true,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 1
        },
        {
          "slug": "anne-blanc",
          "nome": "Anne Blanc",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "demissy",
          "nome": "DeMissy",
          "arquetipo": "",
          "tem_conta": true,
          "email": "comercial.danque@gmail.com",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "gitaa",
          "nome": "Gitaa",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano",
          "nome": "Murano",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "murano-filial",
          "nome": "Murano filial",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "stefani",
          "nome": "Stefani",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "trimix",
          "nome": "Trimix",
          "arquetipo": "heroi",
          "tem_conta": true,
          "email": "salomon@trimix.com.br",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 1,
          "buscas": 1,
          "descricoes": 1,
          "envios": 0,
          "primeiro": "2026-08-14T11:49:43.332Z",
          "ultimo": "2026-08-14T11:49:55.525Z",
          "dias": 1,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "slug": "ttng",
          "nome": "TTNG",
          "arquetipo": "",
          "tem_conta": false,
          "email": "",
          "produtos": 0,
          "estimado": false,
          "produtos_7d": 0,
          "ativa": false,
          "acessos": 0,
          "buscas": 0,
          "descricoes": 0,
          "envios": 0,
          "primeiro": "",
          "ultimo": "",
          "dias": null,
          "produtos_medidos": 0,
          "atribuido": 0
        }
      ],
      "semanas": [
        {
          "inicio": "2026-05-25",
          "fim": "2026-05-31",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-01",
          "fim": "2026-06-07",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-08",
          "fim": "2026-06-14",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-15",
          "fim": "2026-06-21",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-22",
          "fim": "2026-06-28",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-06-29",
          "fim": "2026-07-05",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-06",
          "fim": "2026-07-12",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 0,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-13",
          "fim": "2026-07-19",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 3,
          "novos": 3,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-20",
          "fim": "2026-07-26",
          "produtos": 0,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 0
        },
        {
          "inicio": "2026-07-27",
          "fim": "2026-08-02",
          "produtos": 13,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 5,
          "novos": 0,
          "produtos_medidos": 0,
          "atribuido": 13
        },
        {
          "inicio": "2026-08-03",
          "fim": "2026-08-09",
          "produtos": 21,
          "ativas": 0,
          "usaram": 0,
          "cadastros": 7,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 21
        },
        {
          "inicio": "2026-08-10",
          "fim": "2026-08-16",
          "produtos": 93,
          "ativas": 0,
          "usaram": 3,
          "cadastros": 9,
          "novos": 2,
          "produtos_medidos": 0,
          "atribuido": 93
        }
      ]
    }
  }
};
