window.DADOS = {
  "gerado_em": "2026-08-10T16:58:40.090Z",
  "hoje": "2026-08-10",
  "medindo_desde": "2026-07-24T17:20:05.000Z",
  "criterio": {
    "produtos_semana": 2,
    "dias_parada": 7,
    "janela_dias": 7,
    "semanas": 12
  },
  "kpis": {
    "liberadas": 15,
    "ativas": 4,
    "usando": 8,
    "nunca_usaram": 7,
    "paradas": 1,
    "com_conta": 9,
    "contas": 8,
    "produtos_total": 131,
    "produtos_7d": 17,
    "descricoes_total": 66,
    "total_estimado": true
  },
  "marcas": [
    {
      "slug": "amiska",
      "nome": "Amiska",
      "arquetipo": "sabio",
      "tem_conta": true,
      "email": "missmilliebr@gmail.com",
      "produtos": 46,
      "estimado": true,
      "produtos_7d": 9,
      "ativa": true,
      "acessos": 3,
      "buscas": 18,
      "descricoes": 19,
      "envios": 19,
      "primeiro": "2026-07-28T18:41:18.639Z",
      "ultimo": "2026-08-05T15:40:06.891Z",
      "dias": 5
    },
    {
      "slug": "petit",
      "nome": "Petit",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "anderson@mundotaci.com.br",
      "produtos": 43,
      "estimado": true,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "2026-07-22T20:22:50.872Z",
      "dias": 18
    },
    {
      "slug": "opera-kids",
      "nome": "Ópera Kids",
      "arquetipo": "inocente",
      "tem_conta": true,
      "email": "contato@operakids.com.br",
      "produtos": 36,
      "estimado": true,
      "produtos_7d": 2,
      "ativa": true,
      "acessos": 42,
      "buscas": 50,
      "descricoes": 17,
      "envios": 12,
      "primeiro": "2026-07-28T11:47:18.529Z",
      "ultimo": "2026-08-10T14:28:08.264Z",
      "dias": 0
    },
    {
      "slug": "optimist-jeans",
      "nome": "Optimist Jeans",
      "arquetipo": "governante",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 3,
      "estimado": false,
      "produtos_7d": 3,
      "ativa": true,
      "acessos": 3,
      "buscas": 3,
      "descricoes": 4,
      "envios": 5,
      "primeiro": "2026-08-07T13:23:05.929Z",
      "ultimo": "2026-08-07T14:55:31.596Z",
      "dias": 3
    },
    {
      "slug": "optimist-feirinha",
      "nome": "Optimist Feirinha",
      "arquetipo": "",
      "tem_conta": true,
      "email": "ecommerce@optimistjeans.com.br",
      "produtos": 2,
      "estimado": false,
      "produtos_7d": 2,
      "ativa": true,
      "acessos": 0,
      "buscas": 1,
      "descricoes": 0,
      "envios": 2,
      "primeiro": "2026-08-07T13:33:14.591Z",
      "ultimo": "2026-08-07T14:33:01.598Z",
      "dias": 3
    },
    {
      "slug": "monnika-marikinha",
      "nome": "Monnika Marikinha",
      "arquetipo": "amante",
      "tem_conta": true,
      "email": "monnikamarikinhaloja@gmail.com",
      "produtos": 1,
      "estimado": false,
      "produtos_7d": 1,
      "ativa": false,
      "acessos": 2,
      "buscas": 1,
      "descricoes": 1,
      "envios": 1,
      "primeiro": "2026-08-06T14:16:43.085Z",
      "ultimo": "2026-08-06T14:20:20.569Z",
      "dias": 4
    },
    {
      "slug": "andressa-vesti",
      "nome": "Andressa Vesti",
      "arquetipo": "rebelde",
      "tem_conta": true,
      "email": "andressavazpinto@gmail.commx",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 2,
      "buscas": 1,
      "descricoes": 1,
      "envios": 0,
      "primeiro": "2026-08-10T16:01:03.796Z",
      "ultimo": "2026-08-10T16:09:28.039Z",
      "dias": 0
    },
    {
      "slug": "anne-blanc",
      "nome": "Anne Blanc",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "demissy",
      "nome": "DeMissy",
      "arquetipo": "",
      "tem_conta": true,
      "email": "comercial.danque@gmail.com",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "gitaa",
      "nome": "Gitaa",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano",
      "nome": "Murano",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "murano-filial",
      "nome": "Murano filial",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "stefani",
      "nome": "Stefani",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    },
    {
      "slug": "trimix",
      "nome": "Trimix",
      "arquetipo": "heroi",
      "tem_conta": true,
      "email": "salomon@trimix.com.br",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 7,
      "buscas": 25,
      "descricoes": 24,
      "envios": 0,
      "primeiro": "2026-08-04T14:28:52.117Z",
      "ultimo": "2026-08-06T11:32:52.497Z",
      "dias": 4
    },
    {
      "slug": "ttng",
      "nome": "TTNG",
      "arquetipo": "",
      "tem_conta": false,
      "email": "",
      "produtos": 0,
      "estimado": false,
      "produtos_7d": 0,
      "ativa": false,
      "acessos": 0,
      "buscas": 0,
      "descricoes": 0,
      "envios": 0,
      "primeiro": "",
      "ultimo": "",
      "dias": null
    }
  ],
  "semanas": [
    {
      "inicio": "2026-05-25",
      "fim": "2026-05-31",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-01",
      "fim": "2026-06-07",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-08",
      "fim": "2026-06-14",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-15",
      "fim": "2026-06-21",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-22",
      "fim": "2026-06-28",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-06-29",
      "fim": "2026-07-05",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-06",
      "fim": "2026-07-12",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 0,
      "novos": 0
    },
    {
      "inicio": "2026-07-13",
      "fim": "2026-07-19",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 3,
      "novos": 3
    },
    {
      "inicio": "2026-07-20",
      "fim": "2026-07-26",
      "produtos": 0,
      "ativas": 0,
      "usaram": 0,
      "cadastros": 5,
      "novos": 2
    },
    {
      "inicio": "2026-07-27",
      "fim": "2026-08-02",
      "produtos": 13,
      "ativas": 2,
      "usaram": 2,
      "cadastros": 5,
      "novos": 0
    },
    {
      "inicio": "2026-08-03",
      "fim": "2026-08-09",
      "produtos": 21,
      "ativas": 4,
      "usaram": 6,
      "cadastros": 7,
      "novos": 2
    },
    {
      "inicio": "2026-08-10",
      "fim": "2026-08-16",
      "produtos": 1,
      "ativas": 0,
      "usaram": 2,
      "cadastros": 8,
      "novos": 1
    }
  ]
};
